# Generated by Django 4.2.5 on 2023-10-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escribania', '0002_escribano_caracter_actoescribano_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActoEscritura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escribania.actojuridico', verbose_name='Acto Jurídico')),
            ],
        ),
        migrations.RemoveField(
            model_name='escribano',
            name='actos_juridicos',
        ),
        migrations.RemoveField(
            model_name='escritura',
            name='acto',
        ),
        migrations.DeleteModel(
            name='ActoEscribano',
        ),
        migrations.AddField(
            model_name='actoescritura',
            name='escritura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escribania.escritura', verbose_name='Escritura'),
        ),
        migrations.AddField(
            model_name='escritura',
            name='acto',
            field=models.ManyToManyField(blank=True, null=True, through='escribania.ActoEscritura', to='escribania.actojuridico', verbose_name='Acto Jurídico'),
        ),
    ]
