# Generated by Django 4.2.5 on 2023-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escribania', '0003_actoescritura_remove_escribano_actos_juridicos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritura',
            name='acto',
            field=models.ManyToManyField(blank=True, through='escribania.ActoEscritura', to='escribania.actojuridico', verbose_name='Acto Jurídico'),
        ),
    ]
